### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by yy037** [Moraxyc/Bililiveauto#10]
安装依赖时报错
pm WARN Bililiveauto No repository field.
npm WARN Bililiveauto No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rclone.js@0.6.6 postinstall: `node bin/rclone.js selfupdate`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rclone.js@0.6.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-08-10T04_51_17_116Z-debug.log
[2023-08-10T04_51_17_116Z-debug.txt](https://github.com/Moraxyc/Bililiveauto/files/12308916/2023-08-10T04_51_17_116Z-debug.txt)

**Comment by Moraxyc** [comment]
你的node版本过低
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
```
可以看到，你的node是v10，但目前的LTS是18，建议从[官网](https://nodejs.org/zh-cn)下载lts版本
