### ISSUE TITLE
Google Drive允许同名文件的Bug

### ISSUE THREAD

**Issue by moonmusicstone** [Moraxyc/Bililiveauto#12]
使用新版本脚本上传Google Drive时，由于Google Drive允许同一路径下可以有同名文件，在上传时会生成两个同名文件夹，文件会随机上传到其中任意一个，最后结果就是文件列表变得混乱，但我切换至旧版脚本使用后，似乎不会发生这样的问题。

**Comment by Moraxyc** [comment]
新旧脚本都使用rclone来上传文件，理论上不会发生行为不同的情况才对。新版的主要语言为javascript而旧版的文件处理方面更多以shell调用子进程为主，可能在执行逻辑上更加有优势，在性能表现上更好（虽然也更缝合怪）。我计划对该脚本进行重构，但目前的时间不足，很抱歉没办法及时给予你帮助

**Comment by moonmusicstone** [comment]
我使用回了旧版脚本，目前运行良好，脚本使用体验很好，非常感谢
