### ISSUE TITLE
不清楚脚本是否正常运行

### ISSUE THREAD

**Issue by Jue-Xu** [Moraxyc/Bililiveauto#4]
我的工作目录和设置.env 如下：

<img width="768" alt="image" src="https://user-images.githubusercontent.com/16731479/219576359-8a69b117-1056-4d3f-bb68-f491700d32c0.png">

录播姬正常运行并且已经设置了webhook V2为 http://127.0.0.1:2357 

但是我打开 2357端口的网页显示 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/16731479/219577429-d36a09ea-5ed9-49c2-9d66-c85b424f75f4.png">
并且运行 `pm2 logs bililiveauto` 只显示了 `0|bililive | BiliLiveAuto脚本正在运行, 地址为 http://:::2357`

所以我不清楚脚本是否正常运行，希望能指点一下

**Comment by Moraxyc** [comment]
可以尝试录一个正在直播的直播间再手动暂停来测试下是否工作正常

若后台有“webhook到达”提醒，则表明录播姬到脚本的通信正常

若tg通知未到达，表明脚本与tg不可通信

若rclone未上传，表明rclone相关配置项可能存在错误

除此之外还可以排查下防火墙等设置

**Comment by Jue-Xu** [comment]
好，感谢！我测试一下，过几天再来回复

**Comment by Jue-Xu** [comment]
> 可以尝试录一个正在直播的直播间再手动暂停来测试下是否工作正常
> 
> 若后台有“webhook到达”提醒，则表明录播姬到脚本的通信正常
> 
> 若tg通知未到达，表明脚本与tg不可通信
> 
> 若rclone未上传，表明rclone相关配置项可能存在错误
> 
> 除此之外还可以排查下防火墙等设置

这几项都没有正常工作，不知道怎么debug

**Comment by Moraxyc** [comment]
先通过`lsof`确定脚本是否在监听该端口，出现了运行正常的提示

**Comment by Moraxyc** [comment]
误触了close😅

用`lsof`确定一下脚本是否在监听该端口，如果有监听，就再检查下录播姬的配置，看下录播姬有没有相关报错

按理来讲出现了运行正常提示就说明确实运行正常，如果实在不可用，可以尝试重新按照教程步骤走一遍，或者手动启动几次查看情况

最终无法debug的话可能就是玄学问题了，可以尝试重新安装nodejs和依赖包，更换更高版本
