### ISSUE TITLE
如果不需要弹幕处理是不是直接注释DanmakuFactory地址就可以了

### ISSUE THREAD

**Issue by yy037** [Moraxyc/Bililiveauto#6]
如果不需要弹幕处理是不是直接注释DanmakuFactory地址就可以了

**Comment by Moraxyc** [comment]
不，删掉`runbash.sh`内最后几行中有关弹幕处理的部分即可

**Comment by yy037** [comment]
新版本如果不需要弹幕处理应该怎么操作阿

**Comment by Moraxyc** [comment]
@yy037 刚更新了文件处理逻辑，`.env`中设置`PROCESS_DANMU`为`false`即可

但我还没测试过，应该没问题（
