### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by yy037** [Moraxyc/Bililiveauto#7]
![截图_20230309193811](https://user-images.githubusercontent.com/89193914/224012328-e6deb78e-0295-4597-902c-83f070a61a80.png)

**Comment by Moraxyc** [comment]
依赖没安装

**Comment by yy037** [comment]
你好，请问是哪个依赖

> 依赖未安装

**Comment by yy037** [comment]
谢谢，解决哩
